Feature/docker healthcheck
secureCodeBox/scanner-infrastructure-sslyze pull request #2
Opened 2018-11-08 13:31 UTC by bitofant

added nodejs based health check for docker container health management. Healthcheck.js contains commented hints on how to extend status page parsing. The current implementation is based solely on the http status code.

2018-11-08 15:56 UTC, MartinLang1 requested changes

2018-11-08 15:56 UTC, MartinLang1 commented on Dockerfile
> +HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD node healthcheck.js || exit 1
same comment as in nmap

2018-11-08 15:56 UTC, MartinLang1 commented on healthcheck.js
> +	*/
same comment as nmap pr

2018-11-09 14:42 UTC, bitofant commented on Dockerfile
> +HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 CMD node healthcheck.js || exit 1
All scanners now have a 5s interval

2018-11-09 14:43 UTC, bitofant commented on healthcheck.js
> +	*/
improved this file

2018-11-13 14:03 UTC, merged